import api.Calculator;
import api.API;
import com.fasterxml.jackson.databind.JsonNode;
import com.formdev.flatlaf.FlatDarkLaf;
import components.piechart.PieData;
import java.util.HashMap;
import javax.swing.ImageIcon;

public class Main extends javax.swing.JFrame implements Fonts, Colors {

    private final HashMap<String, Integer> schemesHash = new HashMap<>();
    
    public Main() {
        initComponents();
        getContentPane().setBackground(mainBackground);
        
        API.getAllSchemes().forEach((JsonNode scheme) -> {
            int schemeCode = scheme.get("schemeCode").asInt();
            String schemeName = scheme.get("schemeName").asText();
            schemesHash.put(schemeName, schemeCode);
        });
        
        schemeName.addItems(schemesHash);
        schemeName.setCurrentValue(127042);
        
        compute();
    }
    
    private void compute() {
        if (duration.getText().equals("")) return;
        
        int p = amountSlider.getValue();
        int n = durationSlider.getValue() * 12;
        double r = API.getSchemeReturns(schemeName.getCurrentValue());
        
        int totalInvested = p * n;
        int total = Calculator.getTotalAmount(p, n, r, totalInvested);
        int totalReturns = total - totalInvested;

        invested.setValue(totalInvested);
        returns.setValue(totalReturns);
        totalValue.setValue(total);
        
        returnsDisplay.setValue(r * 12);
        changeReturnsDisplayColor(r >= 0);
        
        graph.clearData();
        graph.addData(new PieData(totalInvested, graphSecondary));
        graph.addData(new PieData(Math.max(0, totalReturns), graphPrimary));

    }
    
    private void changeReturnsDisplayColor(boolean state) {
        if (state)
            returnsDisplay.setForeground(greenForeground);
        else
            returnsDisplay.setForeground(redForeground);
    }
    
    private void changeInputBoxColor(javax.swing.JComponent label, boolean state) {
        if (state) {
            label.setBackground(greenBackground);
            label.setForeground(greenForeground);
        } else {
            label.setBackground(redBackground);
            label.setForeground(redForeground);
        }
    }
    
    private void onKeyReleasedForInput(javax.swing.JFormattedTextField input, javax.swing.JSlider slider) {
        String typed = input.getText();
        
        if (!typed.matches("\\d+")) {
            typed = typed.replaceAll("[^\\d]", "");
            
            if (typed.length() == 0) {
                input.setText("");
                return;
            }
        }
        
        int maxAmount = slider.getMaximum();
        int typedAmount = Math.min(maxAmount, Integer.parseInt(typed));
        
        slider.setValue(typedAmount);
        input.setValue(typedAmount);
        input.setCaretPosition(input.getText().length());
        changeInputBoxColor(input, typedAmount >= slider.getMinimum());
        
        compute();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parametersContainer = new javax.swing.JPanel();
        amountContainer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        amountSlider = new javax.swing.JSlider();
        jLabel12 = new javax.swing.JLabel();
        amount = new javax.swing.JFormattedTextField();
        durationContainer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        durationSlider = new javax.swing.JSlider();
        duration = new javax.swing.JFormattedTextField();
        resultsContainer = new javax.swing.JPanel();
        investedContainer = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        invested = new javax.swing.JFormattedTextField();
        investedContainer3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        returns = new javax.swing.JFormattedTextField();
        investedContainer4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        totalValue = new javax.swing.JFormattedTextField();
        resultsContainer1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        graph = new components.piechart.PieChart();
        schemeContainer = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        amountContainer1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        returnsDisplay = new javax.swing.JFormattedTextField();
        schemeName = new components.autofill.AutofillField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mutual Funds Calculator");
        setBackground(mainBackground);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage((new ImageIcon("../../../Icon.ico").getImage()));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setResizable(false);

        parametersContainer.setBackground(mainBackground);
        parametersContainer.setBorder(new javax.swing.border.LineBorder(secondaryBorder, 2, true));

        amountContainer.setBackground(secondaryBackground);
        amountContainer.setBorder(new javax.swing.border.LineBorder(primaryBorder, 3, true));

        jLabel2.setFont(semiBold18);
        jLabel2.setForeground(primaryForeground);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("₹");

        amountSlider.setBackground(tertiaryBackground);
        amountSlider.setForeground(greenForeground);
        amountSlider.setMajorTickSpacing(1000);
        amountSlider.setMaximum(1000000);
        amountSlider.setMinimum(250);
        amountSlider.setMinorTickSpacing(1);
        amountSlider.setSnapToTicks(true);
        amountSlider.setToolTipText("");
        amountSlider.setValue(25000);
        amountSlider.setFocusable(false);
        amountSlider.setName(""); // NOI18N
        amountSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                amountSliderMouseDragged(evt);
            }
        });

        jLabel12.setBackground(secondaryBackground);
        jLabel12.setFont(medium14);
        jLabel12.setForeground(primaryForeground);
        jLabel12.setText("Monthly investment");
        jLabel12.setToolTipText("");

        amount.setBackground(greenBackground);
        amount.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        amount.setForeground(greenForeground);
        amount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        amount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        amount.setText("25,000");
        amount.setFont(normal18);
        amount.setVerifyInputWhenFocusTarget(false);
        amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout amountContainerLayout = new javax.swing.GroupLayout(amountContainer);
        amountContainer.setLayout(amountContainerLayout);
        amountContainerLayout.setHorizontalGroup(
            amountContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(amountContainerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(amountContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(amountSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(amountContainerLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amount)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        amountContainerLayout.setVerticalGroup(
            amountContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(amountContainerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(amountContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        durationContainer.setBackground(secondaryBackground);
        durationContainer.setBorder(new javax.swing.border.LineBorder(primaryBorder, 3, true));

        jLabel3.setBackground(secondaryBackground);
        jLabel3.setFont(medium14);
        jLabel3.setForeground(primaryForeground);
        jLabel3.setText("Time period");
        jLabel3.setToolTipText("");

        jLabel4.setFont(semiBold18);
        jLabel4.setForeground(primaryForeground);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Yr");

        durationSlider.setBackground(tertiaryBackground);
        durationSlider.setForeground(greenForeground);
        durationSlider.setMajorTickSpacing(5);
        durationSlider.setMaximum(40);
        durationSlider.setMinimum(1);
        durationSlider.setMinorTickSpacing(1);
        durationSlider.setSnapToTicks(true);
        durationSlider.setToolTipText("");
        durationSlider.setValue(10);
        durationSlider.setFocusable(false);
        durationSlider.setName(""); // NOI18N
        durationSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                durationSliderMouseDragged(evt);
            }
        });

        duration.setBackground(greenBackground);
        duration.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        duration.setForeground(greenForeground);
        duration.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        duration.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        duration.setText("10");
        duration.setFont(normal18);
        duration.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                durationKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout durationContainerLayout = new javax.swing.GroupLayout(durationContainer);
        durationContainer.setLayout(durationContainerLayout);
        durationContainerLayout.setHorizontalGroup(
            durationContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(durationContainerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(durationContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(durationSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(durationContainerLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(duration)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        durationContainerLayout.setVerticalGroup(
            durationContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(durationContainerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(durationContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(durationSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout parametersContainerLayout = new javax.swing.GroupLayout(parametersContainer);
        parametersContainer.setLayout(parametersContainerLayout);
        parametersContainerLayout.setHorizontalGroup(
            parametersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parametersContainerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(parametersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amountContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durationContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        parametersContainerLayout.setVerticalGroup(
            parametersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parametersContainerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(amountContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(durationContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        resultsContainer.setBackground(mainBackground);
        resultsContainer.setBorder(new javax.swing.border.LineBorder(secondaryBorder, 2, true));

        investedContainer.setBackground(secondaryBackground);
        investedContainer.setBorder(new javax.swing.border.LineBorder(primaryBorder, 3, true));

        jLabel13.setBackground(secondaryBackground);
        jLabel13.setFont(medium14);
        jLabel13.setForeground(secondaryForeground);
        jLabel13.setText("Invested amount");
        jLabel13.setToolTipText("");

        invested.setEditable(false);
        invested.setBackground(secondaryBackground);
        invested.setBorder(null);
        invested.setForeground(primaryForeground);
        invested.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0"))));
        invested.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        invested.setText("₹0");
        invested.setFocusable(false);
        invested.setFont(semiBold18);
        invested.setRequestFocusEnabled(false);

        javax.swing.GroupLayout investedContainerLayout = new javax.swing.GroupLayout(investedContainer);
        investedContainer.setLayout(investedContainerLayout);
        investedContainerLayout.setHorizontalGroup(
            investedContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(investedContainerLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invested, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        investedContainerLayout.setVerticalGroup(
            investedContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(investedContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(investedContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(investedContainerLayout.createSequentialGroup()
                        .addComponent(invested)
                        .addGap(7, 7, 7))
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        investedContainer3.setBackground(secondaryBackground);
        investedContainer3.setBorder(new javax.swing.border.LineBorder(primaryBorder, 3, true));

        jLabel14.setBackground(secondaryBackground);
        jLabel14.setFont(medium14);
        jLabel14.setForeground(secondaryForeground);
        jLabel14.setText("Est. returns");
        jLabel14.setToolTipText("");

        returns.setEditable(false);
        returns.setBackground(secondaryBackground);
        returns.setBorder(null);
        returns.setForeground(primaryForeground);
        returns.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0"))));
        returns.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        returns.setText("₹0");
        returns.setFocusable(false);
        returns.setFont(semiBold18);
        returns.setRequestFocusEnabled(false);

        javax.swing.GroupLayout investedContainer3Layout = new javax.swing.GroupLayout(investedContainer3);
        investedContainer3.setLayout(investedContainer3Layout);
        investedContainer3Layout.setHorizontalGroup(
            investedContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(investedContainer3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returns, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        investedContainer3Layout.setVerticalGroup(
            investedContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(investedContainer3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(investedContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returns))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        investedContainer4.setBackground(secondaryBackground);
        investedContainer4.setBorder(new javax.swing.border.LineBorder(primaryBorder, 3, true));

        jLabel15.setBackground(secondaryBackground);
        jLabel15.setFont(medium14);
        jLabel15.setForeground(secondaryForeground);
        jLabel15.setText("Total value");
        jLabel15.setToolTipText("");

        totalValue.setEditable(false);
        totalValue.setBackground(secondaryBackground);
        totalValue.setBorder(null);
        totalValue.setForeground(primaryForeground);
        totalValue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0"))));
        totalValue.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        totalValue.setText("₹0");
        totalValue.setFocusable(false);
        totalValue.setFont(semiBold18);
        totalValue.setRequestFocusEnabled(false);

        javax.swing.GroupLayout investedContainer4Layout = new javax.swing.GroupLayout(investedContainer4);
        investedContainer4.setLayout(investedContainer4Layout);
        investedContainer4Layout.setHorizontalGroup(
            investedContainer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(investedContainer4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        investedContainer4Layout.setVerticalGroup(
            investedContainer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(investedContainer4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(investedContainer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalValue))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout resultsContainerLayout = new javax.swing.GroupLayout(resultsContainer);
        resultsContainer.setLayout(resultsContainerLayout);
        resultsContainerLayout.setHorizontalGroup(
            resultsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsContainerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(resultsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(investedContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(investedContainer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(investedContainer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        resultsContainerLayout.setVerticalGroup(
            resultsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsContainerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(investedContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(investedContainer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(investedContainer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        resultsContainer1.setBackground(mainBackground);
        resultsContainer1.setBorder(new javax.swing.border.LineBorder(secondaryBorder, 2, true));

        jLabel16.setBackground(mainBackground);
        jLabel16.setFont(normal14);
        jLabel16.setForeground(primaryForeground);
        jLabel16.setText("Invested amount");
        jLabel16.setToolTipText("");

        jLabel7.setBackground(graphPrimary);
        jLabel7.setOpaque(true);

        jLabel18.setBackground(mainBackground);
        jLabel18.setFont(normal14);
        jLabel18.setForeground(primaryForeground);
        jLabel18.setText("Est. returns");
        jLabel18.setToolTipText("");

        jLabel1.setBackground(graphSecondary);
        jLabel1.setOpaque(true);

        graph.setBackground(mainBackground);

        javax.swing.GroupLayout resultsContainer1Layout = new javax.swing.GroupLayout(resultsContainer1);
        resultsContainer1.setLayout(resultsContainer1Layout);
        resultsContainer1Layout.setHorizontalGroup(
            resultsContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsContainer1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(resultsContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(resultsContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        resultsContainer1Layout.setVerticalGroup(
            resultsContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsContainer1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(resultsContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resultsContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        schemeContainer.setBackground(mainBackground);
        schemeContainer.setBorder(new javax.swing.border.LineBorder(secondaryBorder, 2, true));

        jLabel5.setBackground(mainBackground);
        jLabel5.setFont(medium14);
        jLabel5.setForeground(primaryForeground);
        jLabel5.setText("Mutual fund");
        jLabel5.setToolTipText("");

        amountContainer1.setBackground(secondaryBackground);
        amountContainer1.setBorder(new javax.swing.border.LineBorder(primaryBorder, 3, true));
        amountContainer1.setPreferredSize(new java.awt.Dimension(374, 59));

        jLabel17.setBackground(secondaryBackground);
        jLabel17.setFont(medium14);
        jLabel17.setForeground(secondaryForeground);
        jLabel17.setText("Returns (Annualised)");
        jLabel17.setToolTipText("");

        returnsDisplay.setEditable(false);
        returnsDisplay.setBackground(secondaryBackground);
        returnsDisplay.setBorder(null);
        returnsDisplay.setForeground(greenForeground);
        returnsDisplay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));
        returnsDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        returnsDisplay.setText("0.00%");
        returnsDisplay.setToolTipText("");
        returnsDisplay.setFocusable(false);
        returnsDisplay.setFont(semiBold18);

        javax.swing.GroupLayout amountContainer1Layout = new javax.swing.GroupLayout(amountContainer1);
        amountContainer1.setLayout(amountContainer1Layout);
        amountContainer1Layout.setHorizontalGroup(
            amountContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(amountContainer1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnsDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        amountContainer1Layout.setVerticalGroup(
            amountContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(amountContainer1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(amountContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnsDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        schemeName.setBackground(tertiaryBackground);
        schemeName.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 15));
        schemeName.setForeground(secondaryForeground);
        schemeName.setText("Mutual Fund Name");
        schemeName.setFont(normal18);
        schemeName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                schemeNameKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout schemeContainerLayout = new javax.swing.GroupLayout(schemeContainer);
        schemeContainer.setLayout(schemeContainerLayout);
        schemeContainerLayout.setHorizontalGroup(
            schemeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schemeContainerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(schemeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(amountContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                    .addComponent(schemeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        schemeContainerLayout.setVerticalGroup(
            schemeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schemeContainerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(schemeName, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amountContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(parametersContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resultsContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(schemeContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultsContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(resultsContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(schemeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(parametersContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resultsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(40, 40, 40))
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amountSliderMouseDragged
        amount.setValue(amountSlider.getValue());
        compute();
    }//GEN-LAST:event_amountSliderMouseDragged

    private void durationSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_durationSliderMouseDragged
        duration.setValue(durationSlider.getValue());
        compute();
    }//GEN-LAST:event_durationSliderMouseDragged

    private void amountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountKeyReleased
        onKeyReleasedForInput(amount, amountSlider);
    }//GEN-LAST:event_amountKeyReleased

    private void durationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_durationKeyReleased
        onKeyReleasedForInput(duration, durationSlider);
    }//GEN-LAST:event_durationKeyReleased

    private void schemeNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_schemeNameKeyReleased
        compute();
    }//GEN-LAST:event_schemeNameKeyReleased

    public static void main(String args[]) {
        FlatDarkLaf.setup();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField amount;
    private javax.swing.JPanel amountContainer;
    private javax.swing.JPanel amountContainer1;
    private javax.swing.JSlider amountSlider;
    private javax.swing.JFormattedTextField duration;
    private javax.swing.JPanel durationContainer;
    private javax.swing.JSlider durationSlider;
    private components.piechart.PieChart graph;
    private javax.swing.JFormattedTextField invested;
    private javax.swing.JPanel investedContainer;
    private javax.swing.JPanel investedContainer3;
    private javax.swing.JPanel investedContainer4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel parametersContainer;
    private javax.swing.JPanel resultsContainer;
    private javax.swing.JPanel resultsContainer1;
    private javax.swing.JFormattedTextField returns;
    private javax.swing.JFormattedTextField returnsDisplay;
    private javax.swing.JPanel schemeContainer;
    private components.autofill.AutofillField schemeName;
    private javax.swing.JFormattedTextField totalValue;
    // End of variables declaration//GEN-END:variables
}
